// sections/TransparencyAI.tsx
import { Box, Typography, Card, Button, Divider } from "@mui/material";
import { useNavigate } from "react-router-dom";
import bg from "../assets/AI.png";
import Navbar from "../components/Navbar";

export default function TransparencyAI() {
  const navigate = useNavigate();

  return (
    <Box
      sx={{
        minHeight: "100vh",
        backgroundImage: `url(${bg})`,
        backgroundSize: "cover",
        backgroundPosition: "center",
        display: "flex",
        justifyContent: "center",
        alignItems: "flex-start",
        py: 10,
        px: 2,
      }}
    >
      <Navbar onNavigate={() => {}} active="transparency" />

      <Card
        sx={{
          maxWidth: 900,
          width: "100%",
          borderRadius: 3,
          p: 4,
          background: "rgba(23, 22, 22, 0.85)",
          backdropFilter: "blur(12px)",
          boxShadow: "0 8px 30px rgba(0,0,0,0.4)",
          color: "text.primary",
        }}
      >
        {/* Tiêu đề */}
        <Typography
          variant="h4"
          sx={{
            fontWeight: "bold",
            textAlign: "center",
            color: "secondary.main",
            mb: 3,
          }}
        >
          Tính minh bạch khi sử dụng Remini, Clipchamp và Gemini trong dự án
        </Typography>

        {/* 1. Công cụ kỹ thuật được sử dụng */}
        <Box mb={3}>
          <Typography variant="h6" sx={{ fontWeight: 600, mb: 1, color: "secondary.main" }}>
            1. Các công cụ kỹ thuật được sử dụng
          </Typography>
          <Typography>• <b>Remini</b>: phục hồi và nâng cao chất lượng hình ảnh tư liệu gốc, giúp nội dung trực quan và rõ nét hơn.</Typography>
          <Typography>• <b>Clipchamp</b>: tạo giọng đọc AI tự nhiên cho phần thuyết minh, video học tập hoặc flipbook minh họa.</Typography>
          <Typography>• <b>Gemini (Google)</b>: được dùng làm chatbox học tập — hỗ trợ trao đổi, hỏi – đáp, và gợi mở lý thuyết cho các phần nội dung học thuật ở trên.</Typography>
          <Typography sx={{ mt: 1, opacity: 0.85 }}>
            → Cả ba công cụ chỉ mang tính hỗ trợ kỹ thuật, giúp truyền đạt nội dung hiệu quả hơn, chứ không thay thế vai trò biên soạn và tư duy học thuật của sinh viên.
          </Typography>
        </Box>
        <Divider sx={{ my: 2, borderColor: "secondary.main" }} />

        {/* 2. Mục đích sử dụng */}
        <Box mb={3}>
          <Typography variant="h6" sx={{ fontWeight: 600, mb: 1, color: "secondary.main" }}>
            2. Mục đích và giới hạn sử dụng
          </Typography>
          <Typography>• <b>Remini</b>: dùng để khôi phục hình ảnh mờ, cũ hoặc chất lượng thấp, giúp giữ nguyên giá trị tư liệu gốc.</Typography>
          <Typography>• <b>Clipchamp</b>: giúp tạo giọng đọc thuyết minh, nâng cao khả năng tiếp cận cho người học qua hình thức nghe – nhìn.</Typography>
          <Typography>• <b>Gemini</b>: được tích hợp như một <i>chatbox học lý thuyết</i>, giúp người học trao đổi về các chủ đề như “Dân chủ XHCN”, “Nhà nước pháp quyền XHCN”, “Cách mạng Tháng Tám”... theo hướng phản biện, đối thoại và làm rõ khái niệm.</Typography>
          <Typography>• Không công cụ nào được phép chỉnh sửa, thay thế hay tạo mới dữ liệu học thuật – tất cả nội dung gốc do sinh viên biên soạn và chịu trách nhiệm.</Typography>
        </Box>
        <Divider sx={{ my: 2, borderColor: "secondary.main" }} />

        {/* 3. Vai trò hỗ trợ */}
        <Box mb={3} sx={{ p: 2, borderRadius: 2, border: "1px solid", borderColor: "secondary.main" }}>
          <Typography variant="h6" sx={{ fontWeight: 600, mb: 1, color: "secondary.main" }}>
            3. Vai trò hỗ trợ – không thay thế
          </Typography>
          <Typography>• Remini chỉ khôi phục ảnh, không tạo hình mới hoặc thêm chi tiết ngoài bản gốc.</Typography>
          <Typography>• Clipchamp chỉ hỗ trợ đọc lại nội dung văn bản có sẵn; không sáng tác hay thêm ý kiến mới.</Typography>
          <Typography>• Gemini chỉ gợi mở và giải thích lý thuyết – giúp người học tự phản biện và hiểu sâu hơn, <b>không thay thế giảng viên hoặc nguồn học thuật chính thống</b>.</Typography>
        </Box>
        <Divider sx={{ my: 2, borderColor: "secondary.main" }} />

        {/* 4. Quy trình ghi nhãn */}
        <Box mb={3}>
          <Typography variant="h6" sx={{ fontWeight: 600, mb: 1, color: "secondary.main" }}>
            4. Quy trình ghi nhãn và kiểm tra
          </Typography>
          <Typography>• Ảnh được phục hồi bằng Remini sẽ ghi chú rõ “Ảnh phục hồi kỹ thuật số (Remini)”.</Typography>
          <Typography>• Giọng đọc AI có chú thích “Voice generated by Clipchamp”.</Typography>
          <Typography>• Chatbox hiển thị “Powered by Gemini – hỗ trợ trao đổi lý thuyết”, để người học phân biệt phản hồi AI và nội dung học thuật chính thức.</Typography>
          <Typography>• Tất cả phản hồi AI đều được kiểm duyệt về ngữ nghĩa, không chứa thông tin sai lệch hoặc xuyên tạc khái niệm học thuật.</Typography>
        </Box>
        <Divider sx={{ my: 2, borderColor: "secondary.main" }} />

        {/* 5. Phạm vi & giới hạn */}
        <Box mb={3}>
          <Typography variant="h6" sx={{ fontWeight: 600, mb: 1, color: "secondary.main" }}>
            5. Phạm vi và giới hạn sử dụng
          </Typography>
          <Typography>• Không sử dụng Remini cho mục đích chỉnh sửa khuôn mặt, vật thể hoặc tái tạo tư liệu lịch sử.</Typography>
          <Typography>• Không dùng Clipchamp để giả giọng người thật hoặc phát ngôn có nội dung nhạy cảm.</Typography>
          <Typography>• Không dùng Gemini để tạo lập luận, dẫn chứng hay kết luận học thuật; chỉ được phép <i>thảo luận và phản biện hỗ trợ người học</i>.</Typography>
        </Box>
        <Divider sx={{ my: 2, borderColor: "secondary.main" }} />

        {/* 6. Tính minh bạch khi dùng Gemini */}
        <Box mb={3}>
          <Typography variant="h6" sx={{ fontWeight: 600, mb: 1, color: "secondary.main" }}>
            6. Tính minh bạch khi sử dụng Gemini làm chatbox học tập lý thuyết
          </Typography>
          <Typography>• Chatbox Gemini được triển khai trong các phần lý thuyết của website (ví dụ: Cách mạng Tháng Tám...).</Typography>
          <Typography>• Mục tiêu của Gemini là giúp người học <b>đặt câu hỏi, đối thoại và tự kiểm tra hiểu biết</b> qua tương tác trực tiếp.</Typography>
          <Typography>• Mọi phản hồi Gemini đều được ghi chú rõ nguồn (AI-generated), giúp đảm bảo tính minh bạch và phân biệt với phần nội dung do sinh viên viết.</Typography>
          <Typography>• Việc tích hợp Gemini nhằm khuyến khích <b>tư duy phản biện</b> và <b>tự học có hướng dẫn</b>, không thay thế vai trò của giảng viên hay tài liệu gốc.</Typography>
        </Box>
        <Divider sx={{ my: 2, borderColor: "secondary.main" }} />

        {/* 7. Cam kết minh bạch */}
        <Box mb={4}>
          <Typography variant="h6" sx={{ fontWeight: 600, mb: 1, color: "secondary.main" }}>
            7. Cam kết minh bạch và liêm chính học thuật
          </Typography>
          <Typography>• Toàn bộ nội dung học thuật, lập luận và trích dẫn đều do sinh viên tự biên soạn và chịu trách nhiệm.</Typography>
          <Typography>• Công khai rõ nơi sử dụng AI, phân biệt giữa công cụ hỗ trợ kỹ thuật (Remini, Clipchamp, Gemini) và phần học thuật gốc.</Typography>
          <Typography>• Mọi yêu cầu kiểm chứng đều có thể đáp ứng bằng bản gốc, prompt log hoặc metadata sử dụng AI.</Typography>
        </Box>

        {/* Nút quay lại */}
        <Box sx={{ textAlign: "center" }}>
          <Button
            variant="contained"
            color="primary"
            sx={{ fontWeight: 700, px: 4, borderRadius: "999px" }}
            onClick={() => navigate("/")}
          >
            ← Về trang chủ
          </Button>
        </Box>
      </Card>
    </Box>
  );
}
